install: true
language: node_js
node_js:
  - "11"
addons:
  apt:
    packages:
      - "gcc"
      - "g++"
      - "make"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn run test
cache:
  yarn: true
notifications:
  slack: moonbase-labs:Vc6WhXPLuXrPTDhAtg6SPkrd
