services:
- docker
install:
- docker pull justadudewhohacks/opencv-nodejs
script:
- |
  docker run justadudewhohacks/opencv-nodejs -v $(pwd):/app /bin/sh -c "\
      cd /app; \
      apt-get update && apt-get install -y curl gcc g++ make; \
      curl -sL https://deb.nodesource.com/setup_11.x | bash - ; \
      apt-get install -y nodejs; \
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3; \
      export PATH=\"$HOME/.yarn/bin:$PATH\"; \
      export NODE_PATH=/usr/lib/node_modules; \
      export OPENCV4NODEJS_DISABLE_AUTOBUILD=1; \
      yarn; \
      npm install -g codecov; \
      yarn run test-ci; \
      codecov"
notifications:
  slack:
    rooms:
      secure: Lb6fomr8Nj+pFAtMmPPik7Yr7TUzQ1lcdenhwky1tDc+5tImUoUskYSjzIC+E2FAQxSPHR65Zmf5L8p//HJtyc0rUE07ltW6wJtfYVj2+5dlhgYi+c2PdtyHRfEx7FJyeVak1AZFv3vbNn3OZtu1cT2HXUzgH0u7lOM8mZRW3hGu3rHTzpcUn7lGpZGC3EJNE5aqD3ZPX2PaaZc4IjERY5O+fUo5pTPnp8tLbPQ0+ATivKvdS+Wgqav5UdEaiqRwlTe7yR1kzzqrQ3SNAHACmm0u4XePi/myKl8vZGzMtLsfWl9b0SdfBv+uUxZhG4RPEwKcDnexBQ+gDju2zGmckmZGvCLTy1gshxfITfm7bZ2ugX9NEgiQqp3JSFR/8To35l+I4HEIxBuKA3fAUPgijo9cewwy04RDx3D8p1sEfGrZ6d05w/ERVJy/2srNg9/zHQRYwitq54K5LuOABM618XtesdbNe34TEFvCUt4lMDx3XCzkDXIdyMYvqmXtJqBuYzri5QIGTDjtpecYTYDvaeve2n6Sx6DgfUWfc9sQV/gRwdMXBfAHSv8Xe48Lz77znUahFMJXzV06kr3u8vhYuVOWSNuQT7QOxny3acXtQlEPYqoNIKJbvFvp7IuMxyoaPKS9xyYGqKa5/1tjSj5gTKAoSv1rlLEPa2J02+Eybkg=
    on_success: change
    on_failure: change
