version: 2.1
jobs:
  build_and_test:
    docker:
      - image: vanbujm/moonbase-balena:v0.1.0
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

    # run tests!
      - run: yarn test-ci
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test